### ISSUE TITLE
Creator has the ability to end lobby

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-client#13]

**Comment by bhalf** [comment]
https://github.com/sopra-fs24-group-40/mapquestor-client/commit/ae177518e5ff96f4bf775000cb246c7e5cca5a22

**Comment by domeniku7** [comment]
https://github.com/sopra-fs24-group-40/mapquestor-client/commit/afae927bcceca88ef790859fc72e14ee2a602692
