### ISSUE TITLE
Make the map and the type in field

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-client#22]

**Comment by domeniku7** [comment]
https://github.com/sopra-fs24-group-40/mapquestor-client/commit/0322e5a084e529a1f476d98575900d9d809d148a

**Comment by domeniku7** [comment]
https://github.com/sopra-fs24-group-40/mapquestor-client/commit/8db7530d667fd96c820d7bb045acffe7b0beb5df

**Comment by B-M** [comment]
ffb2fe2002cc3b9e9f4200a93f0ead406a649260

**Comment by domeniku7** [comment]
@
