### ISSUE TITLE
create Header in Dashboard

### ISSUE THREAD

**Issue by LaughingF0x** [sopra-fs24-group-40/mapquestor-client#26]

**Comment by B-M** [comment]
f6b26eaaca967f1a02b17fc56a67561554b79f03

**Comment by B-M** [comment]
8319992172ce2de015d6c0a5d7fbbb031586fcec

**Comment by B-M** [comment]
29d232526275e5bcc4d177714ccd9a46a57e0f85

**Comment by B-M** [comment]
ffd609ea995b092a789b9be2791ad18001a676d5
