### ISSUE TITLE
create All Users page overview

### ISSUE THREAD

**Issue by LaughingF0x** [sopra-fs24-group-40/mapquestor-client#28]

**Comment by B-M** [comment]
f03b6b1265f8e80a67ca548941e7f6e9894ba97c

**Comment by B-M** [comment]
23586624fc17275ac8ce99bf212010ca3aafcc21

**Comment by nik-stev** [comment]
These Commit Links were not linked to this Issue: [Commit Link](https://github.com/sopra-fs24-group-40/mapquestor-client/commit/195268599b62ba686cf4af1a36c2f77080df9c11) [Commit Link 2](https://github.com/sopra-fs24-group-40/mapquestor-client/commit/a9f475ca1e70b94535970cee328148e2aa6dd6c9) [Commit Link 3](https://github.com/sopra-fs24-group-40/mapquestor-client/commit/5acd72233065083181555cfb7f5ed4f85a6af6ad)
