### ISSUE TITLE
Search users by username

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-client#38]

**Comment by nik-stev** [comment]
Commit number 117 should have also mentioned this issue: [Commit Link](https://github.com/sopra-fs24-group-40/mapquestor-client/commit/f48ad99b12dd343bc00c14125fe8b2fa3baefe9a)

**Comment by nik-stev** [comment]
This commit should have been linked to this issue: [Commit Link](https://github.com/sopra-fs24-group-40/mapquestor-client/commit/502d846c3a7c0ca1f1ba93809c644caf0d1b38ad)
