### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by domeniku7** [sopra-fs24-group-40/mapquestor-client#44]

**Comment by B-M** [comment]
b12cfee84bd9b0f2d5672742d85cafc7a5c5fc5d

**Comment by nik-stev** [comment]
This commit needs to be linked to this issue. [Commit](https://github.com/sopra-fs24-group-40/mapquestor-client/commit/028bcb03bd44859ca0b8179fdf0db77bc93778e9)
